/**
 * Auto-naming utility for draft Buying Intents
 * Generates temporary names for auto-created Buying Intents
 */

/**
 * Generate an automatic name for a draft Buying Intent
 * Format: "Auto – Supplier {supplier_name} – {YYYY-MM-DD}"
 *
 * @param {Object} supplierQuote - The supplier quote object
 * @param {string} supplierQuote.supplierName - Supplier company name
 * @param {Object} lineItem - Optional line item data for more specific naming
 * @param {string} lineItem.raw_item_name - Raw item name from supplier
 * @returns {string} Auto-generated name
 */
export function generateAutoName(supplierQuote, lineItem = null) {
  const supplierName = supplierQuote?.supplierName || supplierQuote?.supplier_name || 'Unknown';
  const date = new Date().toISOString().split('T')[0]; // YYYY-MM-DD

  return `Auto – Supplier ${supplierName} – ${date}`;
}

/**
 * Check if a Buying Intent name is auto-generated
 * @param {string} name - The Buying Intent name to check
 * @returns {boolean} True if the name appears to be auto-generated
 */
export function isAutoGeneratedName(name) {
  if (!name) return false;
  return name.startsWith('Auto – Supplier ');
}

/**
 * Extract supplier name from an auto-generated name
 * @param {string} name - Auto-generated name
 * @returns {string|null} Supplier name or null if not auto-generated
 */
export function extractSupplierFromAutoName(name) {
  if (!isAutoGeneratedName(name)) return null;

  const match = name.match(/^Auto – Supplier (.+?) – \d{4}-\d{2}-\d{2}$/);
  return match ? match[1] : null;
}
